In [1]:
import pandas as pd
import numpy as np
import math
import random
import copy

# Cosine similarity

In [2]:
#Cosine Similarity funciton
def cosine_similarity(v1,v2):
    sumxx, sumxy, sumyy = 0, 0, 0
    for i in range(len(v1)):
        x = v1[i]
        y = v2[i]
        sumxx += x*x
        sumyy += y*y
        sumxy += x*y
    return sumxy/float(np.sqrt(sumxx*sumyy))


In [3]:
dat=pd.read_csv("E:/Pooja/WA/Package/Web Package/Package/webdata.csv")

In [4]:
dat

Username  UserID      TweetID     EditID Retweet Reply  \
0         TaranakiRC     767  27271511617  271511617      -1    -1   
1         TaranakiRC     767  27164566943  164566943      -1    -1   
2         TaranakiRC     767  26807004989  807004989      -1    -1   
3         TaranakiRC     767  26805061389  805061389      -1    -1   
4         TaranakiRC     767  26687770320  687770320      -1    -1   
...              ...     ...          ...        ...     ...   ...   
9208       Guztavito   98566   9510062848   10062848      -1    -1   
9209       Guztavito   98566   8177162601   77162601      -1    -1   
9210       Guztavito   98566   8139341315   39341315      -1    -1   
9211  streetstarzent  109260  16333920758  333920758      -1    -1   
9212   xlikeaconcert  109493  22443333392  443333392      -1    -1   

                                                Content  
0                   13398336 4157432 10313027 15828417   
1           14020421 3645451 19004055 11211426 7449723   
2     17165572 8043217 20497981 20501853 9923406 205...  
3     17165572 19221243 13954529 6644775 14974745 60...  
4             4760657 20504089 10988009 643140 7099742   
...                                                 ...  
9208  14716083 18264389 6054867 20326553 2325812 176...  
9209  4985204 12712546 11430002 13260747 8373934 648...  
9210  1713510 4072604 17035136 6804720 3966697 37795...  
9211                                  21392888 8467560   
9212  19083970 2136061 12459512 22420558 21750271 73...  

[9213 rows x 7 columns]

# Keywords co-occurence matrix 

In [5]:
#Keyword matrix generation
key=list(dat['Content'])
ukey=set()
for i in range(len(key)):
    lkey=key[i].split()
    for j in range(len(lkey)):
        ukey.add(lkey[j])
ukey=list(ukey)
ukey.sort()
arr1=np.zeros([len(ukey),len(ukey)],dtype=int)

In [6]:
dat.shape

(9213, 7)

In [7]:
arr1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [8]:
for i in range(len(key)):
    k=key[i].split()
    #print(k)
    for j in range(len(k)):
        for k1 in range(j+1,len(k)):
            #print(k1)
            a=k[j]
            a1=ukey.index(a)
            #print(a1)
            b=k[k1]
           
            b1=ukey.index(b)
            #print(b1)
            arr1[a1][b1]=arr1[a1][b1]+1
            #print(arr1[a1][b1])

In [39]:
arr1.shape

(10934, 10934)

# User keyword matrix w.r.t reply and retweet

In [11]:
#user and keywords matrix generation
dat=pd.read_csv("E:/Pooja/WA/Package/Web Package/Package/webdata.csv")

In [12]:
userid=list(dat['UserID'])
u1=list(dat['UserID'])
userid=np.unique(np.array(userid))
userid=np.sort(userid)
userid=list(userid)
rep=list(dat['Reply'])
twt=list(dat['Retweet'])
key=list(dat['Content'])
ukey=set()

In [13]:
for i in range(len(key)):
    lkey=key[i].split()
    for j in range(len(lkey)):
        ukey.add(lkey[j])
ukey=list(ukey)
ukey.sort()

In [14]:
ukey

['1000048',
 '10002940',
 '10003157',
 '10003402',
 '10008722',
 '10011833',
 '10011944',
 '10011992',
 '10013657',
 '10014215',
 '10018217',
 '10019998',
 '10020263',
 '10022814',
 '10025540',
 '10032584',
 '10036932',
 '10039519',
 '10039658',
 '10040963',
 '1004199',
 '10042864',
 '10043550',
 '1004432',
 '10044514',
 '10044866',
 '10047776',
 '10048023',
 '10048755',
 '10055884',
 '10056620',
 '10057156',
 '10057344',
 '10058214',
 '10063881',
 '10064789',
 '10068423',
 '10070044',
 '10070536',
 '10077693',
 '10078055',
 '10078783',
 '1007969',
 '10082472',
 '10082529',
 '10083091',
 '10083338',
 '1008643',
 '10087158',
 '10087891',
 '10089507',
 '10089622',
 '10094251',
 '10094484',
 '10096766',
 '10104229',
 '10104456',
 '10106518',
 '10106852',
 '10109295',
 '10112251',
 '10113198',
 '10114086',
 '1011473',
 '10115288',
 '10117278',
 '10117329',
 '10119812',
 '10120258',
 '10121180',
 '1012209',
 '10123525',
 '10126659',
 '10127280',
 '10127449',
 '10128912',
 '10129062',
 '1012

# User keyword matrix for reply

In [15]:
u_m_rep=np.zeros([len(userid),len(ukey)],dtype=int)

In [16]:
for i in range(len(u1)):
    if(rep[i]!='-1'):
        
        a=u1[i]
        a1=userid.index(a)
        k=key[i].split()
        for j in range(len(k)):
            b=k[j]
            b1=ukey.index(b)
            #print(a1)
            #print(b1)
            u_m_rep[a1][b1]=1

In [17]:
u_m_rep

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# User keyword matrix for retweet

In [18]:
u_m_ret=np.zeros([len(userid),len(ukey)],dtype=int)

In [19]:
for i in range(len(u1)):
    if(twt[i]!='-1'):
        
        a=u1[i]
        a1=userid.index(a)
        k=key[i].split()
        for j in range(len(k)):
            b=k[j]
            b1=ukey.index(b)
            #print(a1)
            #print(b1)
            u_m_ret[a1][b1]=1

In [20]:
u_m_ret

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# Frienship based influence matrix generation

In [21]:
#Friendship based Influence
df=pd.read_csv('E:/Pooja/WA/Package/Web Package/Package/Users.csv')

In [22]:
df

From     To  Time
0           0     11     1
1           0   4893     1
2           0   6855     1
3           1  31794     1
4           2  17292     1
...       ...    ...   ...
111422  49997  36048     1
111423  49997  37009     1
111424  49997  37611     1
111425  49997  40435     1
111426  49997  41809     1

[111427 rows x 3 columns]

In [90]:
#df1 = df.head()

In [23]:
n=26
umatrix=np.zeros([n,n],dtype=float)

In [24]:
for i in range(n):
    for j in range(n):
        umatrix[i][j]=random.choice([0,1])

In [25]:
umat=np.zeros([n,n],dtype=float)
for i in range(n):
    if sum(umatrix[i,:])>0:
        #print(i)
        for j in range(n):
            if sum(umatrix[:,j])>0:
                #print('j:',j)
                umat[i,j]=(umatrix[i,j]/float(sum(umatrix[:,j])))*(math.log(n/float(sum(umatrix[i,:]))))

In [26]:
ucos=np.zeros([n,n])
for i in range(n):
    for j in range(n):
        ucos[i][j]=cosine_similarity(umat[i],umat[j])

# Topic based influence matrix generation

In [41]:
#topic based influence
#n=len(arr1)
n=50

In [42]:
#kmatrix=np.zeros([n,n],dtype=float) #(k*k matrix) with keyword cooccurance count
#for i in range(n):
#    for j in range(n):
#        kmatrix[i][j]=random.randrange(0,10,1)

In [43]:
kmatrix=copy.copy(arr1)

kmat=np.zeros([n,n],dtype=float)

In [44]:
n

50

In [45]:
for i in range(n):
    print(i)
    if sum(kmatrix[i,:])>0:
        #print(i)
        for j in range(n):
            print("j:",j)
            if sum(kmatrix[:,j])>0:
                #print('j:',j)
                kmat[i,j]=(kmatrix[i,j]/float(sum(kmatrix[:,j])))*(math.log((sum(sum(kmatrix)))/float(sum(kmatrix[i,:]))))
                #print(kmat)
                

0
j: 0
j: 1
j: 2
j: 3
j: 4
j: 5
j: 6
j: 7
j: 8
j: 9
j: 10
j: 11
j: 12
j: 13
j: 14
j: 15
j: 16
j: 17
j: 18
j: 19
j: 20
j: 21
j: 22
j: 23
j: 24
j: 25
j: 26
j: 27
j: 28
j: 29
j: 30
j: 31
j: 32
j: 33
j: 34
j: 35
j: 36
j: 37
j: 38
j: 39
j: 40
j: 41
j: 42
j: 43
j: 44
j: 45
j: 46
j: 47
j: 48
j: 49
1
j: 0
j: 1
j: 2
j: 3
j: 4
j: 5
j: 6
j: 7
j: 8
j: 9
j: 10
j: 11
j: 12
j: 13
j: 14
j: 15
j: 16
j: 17
j: 18
j: 19
j: 20
j: 21
j: 22
j: 23
j: 24
j: 25
j: 26
j: 27
j: 28
j: 29
j: 30
j: 31
j: 32
j: 33
j: 34
j: 35
j: 36
j: 37
j: 38
j: 39
j: 40
j: 41
j: 42
j: 43
j: 44
j: 45
j: 46
j: 47
j: 48
j: 49
2
j: 0
j: 1
j: 2
j: 3
j: 4
j: 5
j: 6
j: 7
j: 8
j: 9
j: 10
j: 11
j: 12
j: 13
j: 14
j: 15
j: 16
j: 17
j: 18
j: 19
j: 20
j: 21
j: 22
j: 23
j: 24
j: 25
j: 26
j: 27
j: 28
j: 29
j: 30
j: 31
j: 32
j: 33
j: 34
j: 35
j: 36
j: 37
j: 38
j: 39
j: 40
j: 41
j: 42
j: 43
j: 44
j: 45
j: 46
j: 47
j: 48
j: 49
3
j: 0
j: 1
j: 2
j: 3
j: 4
j: 5
j: 6
j: 7
j: 8
j: 9
j: 10
j: 11
j: 12
j: 13
j: 14
j: 15
j: 16
j: 17
j: 18
j: 19
j: 20
j: 21


In [46]:
kmat

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [47]:
kcos=np.zeros([n,n])
for i in range(n):
    for j in range(n):
        kcos[i][j]=cosine_similarity(kmat[i],kmat[j])

C:\Users\Pooja\anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in double_scalars
  # Remove the CWD from sys.path while we load stuff.


In [48]:
u_m_inf=np.zeros([len(userid),n],dtype=float)
w=[0.5,0.5]
for i in range(len(userid)):
    for j in range(n):
        cmat=[]
        cmat.append(u_m_rep[i,j])
        cmat.append(u_m_ret[i,j])
        print(cmat)
        u_m_inf[i,j]=1/(1+math.exp(-1*(cmat*np.matrix(w).T)))

[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]
[0, 0]

In [49]:
w = [0.5,0.5]
np.matrix(w).T

matrix([[0.5],
        [0.5]])

In [50]:
cmat

[0, 0]

In [51]:
m_u_inf=copy.copy(u_m_inf)
m_u_inf=m_u_inf.T

In [52]:
kinf=np.matrix(u_m_inf)*np.matrix(kcos)*np.matrix(m_u_inf)

# Interation based influence matrix generation

In [53]:
#Interaction based Influence
dat=pd.read_csv("E:/Pooja/WA/Package/Web Package/Package/webdata.csv")

In [54]:
dat = dat.head()

In [55]:
userid=list(dat['UserID'])
u1=list(dat['UserID'])
userid=np.unique(np.array(userid))
userid=np.sort(userid)
userid=list(userid)
arr=np.zeros([len(userid),len(userid)],dtype=int)
u_m_rep=np.zeros([n,len(arr1)],dtype=int)
u_m_ret=np.zeros([n,len(arr1)],dtype=int)
d=list(dat['Reply'])
for i in range(len(d)):
    if(d[i]!='-1'):
        s=str(d[i])
        s=s[-11:]
        #if s in u1:
        #    index = u1.index(s)
        #    print(index)
       
        rid=random.choice(userid)
        ind=userid.index(rid)
        rv=random.randrange(1,4,1)
        ind1=userid.index(u1[i])
        arr[ind1][ind]=rv

In [56]:
d=list(dat['Retweet'])
for i in range(len(d)):
    if(d[i]!='-1'):
        s=str(d[i])
        #if s in u1:
        #    index = u1.index(s)
        #    print(index)
       
        rid=random.choice(userid)
        ind=userid.index(rid)
        rv=random.randrange(1,4,1)
        ind1=userid.index(u1[i])
        arr[ind1][ind]+=rv

In [57]:
n=26
imatrix=np.zeros([n,n],dtype=float) #(u*u matrix) with interaction count
for i in range(len(arr)):
    mip=0
    bo=0
    for j in range(len(arr)):
        eidu=len(arr)-(list(arr[i]).count(0))
        eidv=len(arr)-(list(arr[j]).count(0))
        a1=copy.copy(arr[i])
        for k in range(len(arr)):
            if a1[k]>0:
                a1[k]=1
        a2=copy.copy(arr[j])
        for k in range(len(arr)):
            if a2[k]>0:
                a2[k]=1
        if eidu==0:
            mip=0
        else:
            mip=(len(arr)-list(a1 & a2).count(0))/float(eidu)
        if eidv==0:
            bo=0
        else:
            bo=(len(arr)-list(a1 & a2).count(0))/float(eidv)
        imatrix[i,j]=(0.5*mip)+(0.5*bo)

# Comprehensive influence

In [58]:
#Comprehensive Influence
comp_inf=np.matrix(imatrix)+((0.5*np.matrix(ucos))+(0.5*np.matrix(kinf)))

comp_inf_sum=[]
for i in range(len(comp_inf)):
    comp_inf_sum.append(np.matrix.sum(comp_inf[i]))

In [59]:
print("The most Influential user is: ",userid[comp_inf_sum.index(max(comp_inf_sum))])

The most Influential user is:  767
